--ALTER TABLE EMPLOYEE:
ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID);

--ALTER TABLE WORK_TIME:
ALTER TABLE WORK_TIME
ADD (
CONSTRAINT WORK_TIME_PK PRIMARY KEY(WORKING_DATE, EMPLOYEE_ID), CONSTRAINT WORK_TIME_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
);

--ALTER TABLE SUPPLIER_CONTRACT:
ALTER TABLE SUPPLIER_CONTRACT
ADD CONSTRAINT SUPPLIER_CONTRACT_PK PRIMARY KEY(CONTRACT_ID);

--ALTER TABLE PERSON_IN_CHARGE:
ALTER TABLE PERSON_IN_CHARGE
ADD CONSTRAINT PERSON_IN_CHARGE_PK PRIMARY KEY (PIC_PHONE);

--ALTER TABLE SUPPLIER:
ALTER TABLE SUPPLIER
ADD (
CONSTRAINT SUPPLIER_PK PRIMARY KEY (SUPPLIER_ID), CONSTRAINT SUPPLIER_CONTRACT_FK FOREIGN KEY (CONTRACT_ID) REFERENCES SUPPLIER_CONTRACT (CONTRACT_ID), CONSTRAINT SUPPLIER_PIC_FK FOREIGN KEY (PIC_PHONE) REFERENCES PERSON_IN_CHARGE (PIC_PHONE)
);

--ALTER TABLE PROMOTION:
ALTER TABLE PROMOTION
ADD CONSTRAINT PROMOTION_PK PRIMARY KEY (PROMOTION_ID);

--ALTER TABLE PRODUCT:
ALTER TABLE PRODUCT
ADD (
CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID), CONSTRAINT PRODUCT_FK FOREIGN KEY (PROMOTION_ID) REFERENCES PROMOTION (PROMOTION_ID)
);

--ALTER TABLE SUPPLIER_ORDER:
ALTER TABLE SUPPLIER_ORDER
ADD (
CONSTRAINT SUPPLIER_ORDER_PK PRIMARY KEY (SUPPLIER_ORDER_ID), CONSTRAINT SUPPLIER_ORDER_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES  PRODUCT (PRODUCT_ID), CONSTRAINT SUPPLIER_SUPPLIER_ORDER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID), CONSTRAINT CHECK_SUPPLIER_RESTOCK_QUANTITY CHECK (SUPPLIER_RESTOCK_QUANTITY > 0)
);

--ALTER TABLE RECEIPT_PRODUCT:
ALTER TABLE RECEIPT_PRODUCT
ADD (
CONSTRAINT RECEIPT_PRODUCT_PK PRIMARY KEY (REFERENCE_NO), CONSTRAINT RECEIPT_PRODUCT_RECEIPT_FK FOREIGN KEY (RECEIPT_ID) REFERENCES RECEIPT (RECEIPT_ID), CONSTRAINT RECEIPT_PRODUCT_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID), CONSTRAINT CHECK_PRODUCT_QUANTITY CHECK (PRODUCT_QUANTITY > 0)
);

--ALTER TABLE MEMBER_TYPE:
ALTER TABLE MEMBER_TYPE
ADD CONSTRAINT MEMBER_TYPE_PK PRIMARY KEY (MEMBER_TYPE);

--ALTER TABLE PAYMENT:
ALTER TABLE PAYMENT
ADD CONSTRAINT PAYMENT_PK PRIMARY KEY (PAYMENT_ID);

--ALTER TABLE MEMBERSHIP:
ALTER TABLE MEMBERSHIP
ADD (
CONSTRAINT MEMBERSHIP_PK PRIMARY KEY (MEMBER_ID), CONSTRAINT MEMBERSHIP_FK FOREIGN KEY (MEMBER_TYPE) REFERENCES MEMBER_TYPE (MEMBER_TYPE)
);

--ALTER TABLE RECEIPT:
ALTER TABLE RECEIPT
ADD (
CONSTRAINT RECEIPT_PK PRIMARY KEY (RECEIPT_ID), CONSTRAINT RECEIPT_EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID), CONSTRAINT RECEIPT_MEMBERSHIP_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERSHIP (MEMBER_ID), CONSTRAINT RECEIPT_PAYMENT_FK FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT (PAYMENT_ID)
);

--ALTER TABLE SALES:
ALTER TABLE SALES
ADD (
CONSTRAINT SALES_PK PRIMARY KEY (SALES_ID, RECEIPT_ID), CONSTRAINT SALES_FK FOREIGN KEY (RECEIPT_ID) REFERENCES RECEIPT (RECEIPT_ID)
);