--VIEW TABLE EMPLOYEE:
SELECT * FROM EMPLOYEE;

--VIEW TABLE WORK_TIME:
SELECT * FROM WORK_TIME;

--VIEW TABLE SUPPLIER_CONTRACT:
SELECT * FROM SUPPLIER_CONTRACT;

--VIEW TABLE PERSON_IN_CHARGE:
SELECT * FROM PERSON_IN_CHARGE;

--VIEW TABLE SUPPLIER:
SELECT * FROM SUPPLIER;

--VIEW TABLE PROMOTION:
SELECT * FROM PROMOTION;

--VIEW TABLE PRODUCT:
SELECT * FROM PRODUCT;

--VIEW TABLE SUPPLIER_ORDER:
SELECT * FROM SUPPLIER_ORDER;

--VIEW TABLE RECEIPT_PRODUCT:
SELECT * FROM RECEIPT_PRODUCT;

--VIEW TABLE MEMBER_TYPE:
SELECT * FROM MEMBER_TYPE;

--VIEW TABLE PAYMENT:
SELECT * FROM PAYMENT;

--VIEW TABLE MEMBERSHIP:
SELECT * FROM MEMBERSHIP;

--VIEW TABLE RECEIPT:
SELECT * FROM RECEIPT;

--VIEW TABLE SALES:
SELECT * FROM SALES;
